### ISSUE TITLE
Feature request - support .yaml files as well as .json files for input

### ISSUE THREAD

**Issue by oharboe** [bavovanachte/sphinx-wavedrom#49]
It would be simple to support both. Would such a PR be considered?

yaml and json are equivalent, but I find yaml can be easier on the eye:

```json
{ "signal": [
        { "name": "clk",  "wave": "P......" },
        { "name": "bus",  "wave": "x.==.=x", "data": ["head", "body", "tail", "data"] },
        { "name": "wire", "wave": "0.1..0." }
]}
```

vs

```yaml
signal:
  - name: clk
    wave: P......
  - name: bus
    wave: x.==.=x
    data:
      - head
      - body
      - tail
      - data
  - name: wire
    wave: 0.1..0.
```
